import type {
  AdmissionResult,
  Campus,
  Channel,
  CRMTask,
  CRMUser,
  Enrollment,
  FollowUp,
  Handoff,
  Lead,
  Payment,
  Tag,
} from "@/lib/types";

function isoDaysFromNow(days: number) {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
}

function isoHoursFromNow(hours: number) {
  return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
}

export const campuses: Campus[] = [
  { id: "campus-tokyo", name: "东京校区", city: "东京" },
  { id: "campus-osaka", name: "大阪校区", city: "大阪" },
  { id: "campus-fukuoka", name: "福冈校区", city: "福冈" },
];

export const channels: Channel[] = [
  { id: "ch-xhs", name: "小红书" },
  { id: "ch-douyin", name: "抖音" },
  { id: "ch-bilibili", name: "B站" },
  { id: "ch-wx-mp", name: "微信公众号" },
  { id: "ch-wx-group", name: "微信社群" },
  { id: "ch-moments", name: "朋友圈" },
  { id: "ch-baidu", name: "百度" },
  { id: "ch-zhihu", name: "知乎" },
  { id: "ch-friend", name: "朋友介绍" },
  { id: "ch-old", name: "老生转介绍" },
  { id: "ch-agent", name: "中介合作" },
  { id: "ch-lecture-offline", name: "线下讲座" },
  { id: "ch-lecture-online", name: "线上讲座" },
  { id: "ch-other", name: "其他" },
];

export const users: CRMUser[] = [
  { id: "u-admin", name: "系统管理员", role: "超级管理员", campusId: "campus-tokyo", active: true },
  { id: "u-head-tokyo", name: "田中（东京负责人）", role: "校区负责人", campusId: "campus-tokyo", active: true },
  { id: "u-head-osaka", name: "佐藤（大阪负责人）", role: "校区负责人", campusId: "campus-osaka", active: true },
  { id: "u-consult-a", name: "李顾问", role: "销售顾问", campusId: "campus-tokyo", active: true },
  { id: "u-consult-b", name: "王顾问", role: "销售顾问", campusId: "campus-osaka", active: true },
  { id: "u-consult-c", name: "张顾问", role: "销售顾问", campusId: "campus-tokyo", active: true },
  {
    id: "u-market-1",
    name: "市场-小红书",
    role: "市场人员",
    campusId: "campus-tokyo",
    active: true,
    channelIds: ["ch-xhs"],
  },
  { id: "u-academic-1", name: "教务-陈老师", role: "教务", campusId: "campus-tokyo", active: true },
  { id: "u-guide-1", name: "进学-林老师", role: "进学指导", campusId: "campus-tokyo", active: true },
  { id: "u-finance-1", name: "财务-赵老师", role: "财务", campusId: "campus-tokyo", active: true },
];

export const tags: Tag[] = [
  { id: "tag-high", name: "高优先级", color: "bg-rose-500/15 text-rose-600" },
  { id: "tag-urgent", name: "急需答复", color: "bg-amber-500/15 text-amber-700" },
  { id: "tag-art", name: "美术方向", color: "bg-indigo-500/15 text-indigo-600" },
  { id: "tag-eju", name: "EJU高分", color: "bg-emerald-500/15 text-emerald-700" },
  { id: "tag-budget", name: "预算敏感", color: "bg-zinc-500/15 text-zinc-700" },
];

export const leads: Lead[] = [
  {
    id: "l-001",
    studentName: "陈佳怡",
    wechat: "cjiyi_2026",
    phone: "13800001111",
    email: "jiayi.chen@example.com",
    locationCountry: "中国",
    locationCity: "上海",
    currentSchool: "同济大学",
    currentGrade: "大三",
    targetTrack: "大学院",
    targetYear: 2027,
    targetSchool: "东京大学",
    targetMajor: "情报学",
    japaneseLevel: "N2",
    englishLevel: "CET-6",
    ejuScore: "",
    toeflToeicScore: "TOEFL 92",
    budget: 180000,
    channelId: "ch-xhs",
    campusId: "campus-tokyo",
    ownerId: "u-consult-a",
    customerLevel: "A",
    status: "已预约试听",
    tagIds: ["tag-high"],
    notes: "关注研究计划与教授匹配，倾向一对一规划。",
    nextFollowUpAt: isoHoursFromNow(6),
    createdAt: isoDaysFromNow(-3),
    updatedAt: isoDaysFromNow(-1),
  },
  {
    id: "l-002",
    studentName: "周子涵",
    wechat: "zh_nihon",
    phone: "13900002222",
    email: "zihan.zhou@example.com",
    locationCountry: "日本",
    locationCity: "大阪",
    currentSchool: "关西大学",
    currentGrade: "大二",
    targetTrack: "学部",
    targetYear: 2026,
    targetSchool: "早稻田大学",
    targetMajor: "经济学",
    japaneseLevel: "N1",
    englishLevel: "IELTS 6.0",
    ejuScore: "EJU 310",
    toeflToeicScore: "",
    budget: 120000,
    channelId: "ch-douyin",
    campusId: "campus-osaka",
    ownerId: "u-consult-b",
    customerLevel: "B",
    status: "已报价",
    tagIds: ["tag-urgent"],
    notes: "已收到报价，需跟进家长确认付款方式。",
    nextFollowUpAt: isoHoursFromNow(-3),
    createdAt: isoDaysFromNow(-10),
    updatedAt: isoDaysFromNow(-2),
  },
  {
    id: "l-003",
    studentName: "刘宇航",
    wechat: "liuyh_art",
    phone: "13700003333",
    email: "yuhang.liu@example.com",
    locationCountry: "中国",
    locationCity: "广州",
    currentSchool: "广州美术学院",
    currentGrade: "大四",
    targetTrack: "美术",
    targetYear: 2026,
    targetSchool: "武藏野美术大学",
    targetMajor: "视觉传达",
    japaneseLevel: "N3",
    englishLevel: "",
    ejuScore: "",
    toeflToeicScore: "",
    budget: 220000,
    channelId: "ch-bilibili",
    campusId: "campus-tokyo",
    ownerId: "u-consult-c",
    customerLevel: "A",
    status: "服务中",
    tagIds: ["tag-art", "tag-high"],
    notes: "作品集排期紧张，优先安排每周两次作品集辅导。",
    nextFollowUpAt: isoDaysFromNow(2),
    createdAt: isoDaysFromNow(-25),
    updatedAt: isoDaysFromNow(-1),
  },
  {
    id: "l-004",
    studentName: "孙雨桐",
    wechat: "yutong_sun",
    phone: "13600004444",
    email: "yutong.sun@example.com",
    locationCountry: "中国",
    locationCity: "北京",
    currentSchool: "北京外国语大学",
    currentGrade: "研一",
    targetTrack: "大学院",
    targetYear: 2027,
    targetSchool: "一桥大学",
    targetMajor: "经营学",
    japaneseLevel: "N2",
    englishLevel: "TOEIC 865",
    ejuScore: "",
    toeflToeicScore: "TOEIC 865",
    budget: 160000,
    channelId: "ch-zhihu",
    campusId: "campus-tokyo",
    ownerId: "u-consult-a",
    customerLevel: "B",
    status: "已初次沟通",
    tagIds: [],
    notes: "重点关心校内考与面试策略。",
    nextFollowUpAt: isoDaysFromNow(1),
    createdAt: isoDaysFromNow(-2),
    updatedAt: isoDaysFromNow(-2),
  },
  {
    id: "l-005",
    studentName: "高天宇",
    wechat: "ty_gao_job",
    phone: "13500005555",
    email: "tianyu.gao@example.com",
    locationCountry: "日本",
    locationCity: "东京",
    currentSchool: "明治大学",
    currentGrade: "大四",
    targetTrack: "就职",
    targetYear: 2026,
    targetSchool: "大手メーカー",
    targetMajor: "综合职",
    japaneseLevel: "N1",
    englishLevel: "TOEIC 750",
    ejuScore: "",
    toeflToeicScore: "TOEIC 750",
    budget: 90000,
    channelId: "ch-old",
    campusId: "campus-tokyo",
    ownerId: "u-consult-c",
    customerLevel: "C",
    status: "已缴费",
    tagIds: ["tag-budget"],
    notes: "预算敏感，已选择分期，关注面试练习。",
    nextFollowUpAt: isoDaysFromNow(5),
    createdAt: isoDaysFromNow(-18),
    updatedAt: isoDaysFromNow(-4),
  },
  {
    id: "l-006",
    studentName: "马思雨",
    wechat: "msy_eju",
    phone: "13400006666",
    email: "siyu.ma@example.com",
    locationCountry: "中国",
    locationCity: "成都",
    currentSchool: "成都七中",
    currentGrade: "高三",
    targetTrack: "学部",
    targetYear: 2026,
    targetSchool: "庆应义塾大学",
    targetMajor: "法学",
    japaneseLevel: "N3",
    englishLevel: "IELTS 5.5",
    ejuScore: "EJU 330",
    toeflToeicScore: "",
    budget: 200000,
    channelId: "ch-xhs",
    campusId: "campus-osaka",
    ownerId: "u-consult-b",
    customerLevel: "A",
    status: "已试听",
    tagIds: ["tag-eju"],
    notes: "EJU分数优秀，担心志望理由书表达。",
    nextFollowUpAt: isoHoursFromNow(20),
    createdAt: isoDaysFromNow(-6),
    updatedAt: isoDaysFromNow(-1),
  },
  {
    id: "l-007",
    studentName: "黄若曦",
    wechat: "ruoxi_h",
    phone: "13300007777",
    email: "ruoxi.huang@example.com",
    locationCountry: "日本",
    locationCity: "福冈",
    currentSchool: "九州大学",
    currentGrade: "研二",
    targetTrack: "大学院",
    targetYear: 2026,
    targetSchool: "九州大学",
    targetMajor: "材料科学",
    japaneseLevel: "N1",
    englishLevel: "TOEFL 98",
    ejuScore: "",
    toeflToeicScore: "TOEFL 98",
    budget: 140000,
    channelId: "ch-friend",
    campusId: "campus-fukuoka",
    ownerId: "u-consult-b",
    customerLevel: "B",
    status: "新线索",
    tagIds: [],
    notes: "初步咨询，需添加微信。",
    nextFollowUpAt: isoHoursFromNow(4),
    createdAt: isoDaysFromNow(0),
    updatedAt: isoDaysFromNow(0),
  },
  {
    id: "l-008",
    studentName: "杨晨",
    wechat: "yangchen_n5",
    phone: "13200008888",
    email: "chen.yang@example.com",
    locationCountry: "中国",
    locationCity: "杭州",
    currentSchool: "浙江大学",
    currentGrade: "大二",
    targetTrack: "日语",
    targetYear: 2026,
    targetSchool: "语言学校",
    targetMajor: "",
    japaneseLevel: "N5",
    englishLevel: "",
    ejuScore: "",
    toeflToeicScore: "",
    budget: 50000,
    channelId: "ch-wx-group",
    campusId: "campus-tokyo",
    ownerId: "u-consult-a",
    customerLevel: "D",
    status: "已添加微信",
    tagIds: ["tag-budget"],
    notes: "先学日语再考虑升学方向。",
    nextFollowUpAt: isoDaysFromNow(3),
    createdAt: isoDaysFromNow(-1),
    updatedAt: isoDaysFromNow(-1),
  },
  {
    id: "l-009",
    studentName: "郑泽宇",
    wechat: "zz_reason",
    phone: "13100009999",
    email: "zeyu.zheng@example.com",
    locationCountry: "日本",
    locationCity: "东京",
    currentSchool: "东京外国语大学",
    currentGrade: "大三",
    targetTrack: "大学院",
    targetYear: 2027,
    targetSchool: "京都大学",
    targetMajor: "国际关系",
    japaneseLevel: "N1",
    englishLevel: "IELTS 7.0",
    ejuScore: "",
    toeflToeicScore: "IELTS 7.0",
    budget: 150000,
    channelId: "ch-wx-mp",
    campusId: "campus-tokyo",
    ownerId: "u-consult-c",
    customerLevel: "B",
    status: "已报名",
    tagIds: ["tag-urgent"],
    notes: "志望理由书 deadline 较近，需要排期。",
    nextFollowUpAt: isoDaysFromNow(1),
    createdAt: isoDaysFromNow(-14),
    updatedAt: isoDaysFromNow(-3),
  },
  {
    id: "l-010",
    studentName: "罗婉清",
    wechat: "wq_luo",
    phone: "13000001010",
    email: "wanqing.luo@example.com",
    locationCountry: "中国",
    locationCity: "深圳",
    currentSchool: "深圳大学",
    currentGrade: "大一",
    targetTrack: "学部",
    targetYear: 2028,
    targetSchool: "上智大学",
    targetMajor: "传媒",
    japaneseLevel: "N4",
    englishLevel: "IELTS 5.0",
    ejuScore: "",
    toeflToeicScore: "",
    budget: 130000,
    channelId: "ch-lecture-online",
    campusId: "campus-tokyo",
    ownerId: "u-consult-a",
    customerLevel: "C",
    status: "已发课程介绍",
    tagIds: [],
    notes: "家长想先了解课程体系和师资。",
    nextFollowUpAt: isoHoursFromNow(30),
    createdAt: isoDaysFromNow(-5),
    updatedAt: isoDaysFromNow(-4),
  },
];

export const followUps: FollowUp[] = [
  {
    id: "fu-001",
    leadId: "l-001",
    followUpAt: isoDaysFromNow(-2),
    method: "微信",
    content: "发送课程资料与案例，确认目标院校与时间线。",
    feedback: "学生希望先试听规划课。",
    nextAction: "安排试听时间与老师。",
    nextFollowUpAt: isoHoursFromNow(6),
    operatorId: "u-consult-a",
    statusChangeFrom: "已初次沟通",
    statusChangeTo: "已预约试听",
    createdAt: isoDaysFromNow(-2),
  },
  {
    id: "fu-002",
    leadId: "l-002",
    followUpAt: isoDaysFromNow(-4),
    method: "电话",
    content: "解释报价包含内容与服务周期，确认是否需要分期。",
    feedback: "家长希望再对比两家机构。",
    nextAction: "发送对比清单与时间优惠。",
    nextFollowUpAt: isoHoursFromNow(-3),
    operatorId: "u-consult-b",
    statusChangeFrom: "已试听",
    statusChangeTo: "已报价",
    createdAt: isoDaysFromNow(-4),
  },
  {
    id: "fu-003",
    leadId: "l-003",
    followUpAt: isoDaysFromNow(-1),
    method: "面谈",
    content: "确认作品集方向与每周辅导节奏，分解里程碑。",
    feedback: "学生接受每周两次，想加一次作品点评。",
    nextAction: "教务安排老师与时间。",
    nextFollowUpAt: isoDaysFromNow(2),
    operatorId: "u-consult-c",
    createdAt: isoDaysFromNow(-1),
  },
];

export const enrollments: Enrollment[] = [
  {
    id: "en-001",
    leadId: "l-003",
    courseName: "美术作品集冲刺（12周）",
    courseType: "美术",
    listPrice: 260000,
    discountAmount: 40000,
    paidAmount: 220000,
    paymentStatus: "已付款",
    paymentMethod: "银行转账",
    enrolledAt: isoDaysFromNow(-20),
    serviceStartDate: isoDaysFromNow(-18).slice(0, 10),
    serviceEndDate: isoDaysFromNow(66).slice(0, 10),
    academicAdminId: "u-academic-1",
    teacherId: "u-guide-1",
    campusId: "campus-tokyo",
  },
  {
    id: "en-002",
    leadId: "l-005",
    courseName: "就职面试与ES辅导（8周）",
    courseType: "面试",
    listPrice: 98000,
    discountAmount: 8000,
    paidAmount: 45000,
    paymentStatus: "部分付款",
    paymentMethod: "分期",
    enrolledAt: isoDaysFromNow(-7),
    serviceStartDate: isoDaysFromNow(-6).slice(0, 10),
    serviceEndDate: isoDaysFromNow(50).slice(0, 10),
    academicAdminId: "u-academic-1",
    teacherId: "u-guide-1",
    campusId: "campus-tokyo",
  },
  {
    id: "en-003",
    leadId: "l-009",
    courseName: "志望理由书与研究计划（6周）",
    courseType: "志望理由书",
    listPrice: 128000,
    discountAmount: 0,
    paidAmount: 0,
    paymentStatus: "未付款",
    paymentMethod: "微信",
    enrolledAt: isoDaysFromNow(-3),
    serviceStartDate: isoDaysFromNow(0).slice(0, 10),
    serviceEndDate: isoDaysFromNow(42).slice(0, 10),
    academicAdminId: "u-academic-1",
    teacherId: "u-guide-1",
    campusId: "campus-tokyo",
  },
];

export const payments: Payment[] = [
  {
    id: "pay-001",
    enrollmentId: "en-001",
    amount: 220000,
    method: "银行转账",
    paidAt: isoDaysFromNow(-19),
    note: "一次性付款",
  },
  {
    id: "pay-002",
    enrollmentId: "en-002",
    amount: 45000,
    method: "分期",
    paidAt: isoDaysFromNow(-6),
    note: "第一期",
  },
];

export const handoffs: Handoff[] = [
  {
    id: "ho-001",
    leadId: "l-003",
    enrollmentId: "en-001",
    studyGoal: "完成作品集并在校内考前完成面试作品阐述。",
    targetSchool: "武藏野美术大学",
    currentLevel: "作品集基础较好，表达需要加强。",
    salesPromises: "每周两次作品集辅导 + 1 次作品点评。",
    specialNotes: "对时间安排较敏感，尽量固定在周末。",
    coursesToArrange: "作品集辅导、作品点评、面试练习",
    academicAdminId: "u-academic-1",
    classAssignmentStatus: "已分班",
    confirmStatus: "已确认",
    createdAt: isoDaysFromNow(-19),
    updatedAt: isoDaysFromNow(-18),
  },
  {
    id: "ho-002",
    leadId: "l-009",
    enrollmentId: "en-003",
    studyGoal: "6周内完成志望理由书初稿与三轮修改。",
    targetSchool: "京都大学",
    currentLevel: "写作结构清晰，但语言精炼度不足。",
    salesPromises: "3次深度修改 + 1次模拟面试。",
    specialNotes: "deadline 较近，优先排期。",
    coursesToArrange: "志望理由书辅导、面试练习",
    academicAdminId: "u-academic-1",
    classAssignmentStatus: "未分班",
    confirmStatus: "未确认",
    createdAt: isoDaysFromNow(-2),
    updatedAt: isoDaysFromNow(-2),
  },
];

export const tasks: CRMTask[] = [
  {
    id: "t-001",
    leadId: "l-001",
    assigneeId: "u-consult-a",
    type: "试听提醒",
    title: "安排陈佳怡的规划试听（确认时间与老师）",
    status: "待处理",
    dueAt: isoHoursFromNow(6),
    createdAt: isoDaysFromNow(-2),
  },
  {
    id: "t-002",
    leadId: "l-002",
    assigneeId: "u-consult-b",
    type: "报价后未回复提醒",
    title: "跟进周子涵报价反馈（确认是否报名/付款方式）",
    status: "待处理",
    dueAt: isoHoursFromNow(-3),
    createdAt: isoDaysFromNow(-3),
  },
  {
    id: "t-003",
    leadId: "l-005",
    assigneeId: "u-finance-1",
    type: "缴费提醒",
    title: "高天宇分期第二期收款提醒",
    status: "待处理",
    dueAt: isoDaysFromNow(3),
    createdAt: isoDaysFromNow(-1),
  },
  {
    id: "t-004",
    leadId: "l-009",
    assigneeId: "u-academic-1",
    type: "分班提醒",
    title: "郑泽宇课程分班与老师排期",
    status: "待处理",
    dueAt: isoDaysFromNow(1),
    createdAt: isoDaysFromNow(-2),
  },
  {
    id: "t-005",
    leadId: "l-009",
    assigneeId: "u-guide-1",
    type: "志望理由书截止提醒",
    title: "郑泽宇志望理由书第一轮修改",
    status: "待处理",
    dueAt: isoDaysFromNow(2),
    createdAt: isoDaysFromNow(-1),
  },
];

export const admissionResults: AdmissionResult[] = [
  {
    id: "ar-001",
    leadId: "l-003",
    school: "武藏野美术大学",
    major: "视觉传达",
    level: "本科",
    isFirstChoice: true,
    canMarketing: true,
    admittedAt: isoDaysFromNow(-120),
    consultantId: "u-consult-c",
    teacherId: "u-guide-1",
    marketingAssetStatus: "已整理",
  },
];

export const db = {
  campuses,
  channels,
  users,
  tags,
  leads,
  followUps,
  enrollments,
  payments,
  handoffs,
  tasks,
  admissionResults,
};
